version: '2'

services:

  bot:
    restart: always
    build: .
    working_dir: /tgbot
    volumes:
      - .:/tgbot
    environment:
      - TOKEN=${TOKEN}
    depends_on:
      - mongodb
    links:
      - mongodb
    command: python bot.py

  download_bot:
    restart: always
    build: .
    working_dir: /tgbot
    volumes:
      - .:/tgbot
    environment:
      - TOKEN2=${TOKEN2}
    depends_on:
      - mongodb
    links:
      - mongodb
    command: python download_bot.py

  mongodb:
    restart: always
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/dockerdata/db
    volumes:
          - ./dockerdata/db:/data/db
    ports:
      - 27017:27017
    command: mongod